# setup environment
dist: focal
language: python
cache: pip

branches:
  only:
  - master

notifications:
  email: false

git:
  depth: 5

# setup tests
env:
  global:
  - APM_TEST_PACKAGES='language-ansible'
  - ATOM_LINT_WITH_BUNDLED_NODE='true'

os: linux
python: 3.8

matrix:
  include:
  - env: VERSION=5.0

# execute tests
install:
- pip install "ansible-lint~=${VERSION}"
- pip install ansible
before_script: ansible-lint --version
script: 'curl -s https://raw.githubusercontent.com/mschuchard/vagrant-boxes-docker-images/master/atom-build-package.sh | sh'
